# Generated by Django 2.1.5 on 2019-01-20 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionvote',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='voter'),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Post', verbose_name='voted for'),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='value',
            field=models.IntegerField(default=0, verbose_name='vote value'),
        ),
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together={('author', 'question')},
        ),
    ]
