# Generated by Django 2.1.5 on 2019-01-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
