# Generated by Django 2.1.5 on 2019-01-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20190121_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
    ]
