# Generated by Django 2.1.5 on 2019-01-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.SmallIntegerField(choices=[('UP', 1), ('DOWN', -1)], default=0),
        ),
    ]
